### ISSUE TITLE
Installation geht nicht

### ISSUE THREAD

**Issue by mimquadrat** [ioBroker/ioBroker.zwave#3]
Fehler in Konsole:

gyp ERR! build error 
gyp ERR! stack Error: `make` failed with exit code: 2
gyp ERR! stack     at ChildProcess.onExit (/usr/local/lib/node_modules/npm/node_modules/node-gyp/lib/build.js:267:23)
gyp ERR! stack     at ChildProcess.EventEmitter.emit (events.js:98:17)
gyp ERR! stack     at Process.ChildProcess._handle.onexit (child_process.js:789:12)
gyp ERR! System Linux 3.18.11-v7+
gyp ERR! command "node" "/usr/local/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"
gyp ERR! cwd /opt/iobroker/node_modules/iobroker.zwave/node_modules/openzwave-shared
gyp ERR! node -v v0.10.22
gyp ERR! node-gyp -v v0.11.0
gyp ERR! not ok 
npm ERR! openzwave-shared@1.1.0 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR! 
npm ERR! Failed at the openzwave-shared@1.1.0 install script.
npm ERR! This is most likely a problem with the openzwave-shared package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.

npm ERR! System Linux 3.18.11-v7+
npm ERR! command "/usr/local/bin/node" "/usr/local/bin/npm" "install" "iobroker.zwave"
npm ERR! cwd /opt/iobroker
npm ERR! node -v v0.10.22
npm ERR! npm -v 1.3.14
npm ERR! code ELIFECYCLE
npm ERR! 
npm ERR! Additional logging details can be found in:
npm ERR!     /opt/iobroker/npm-debug.log
npm ERR! not ok code 0

**Comment by sja** [comment]
Me too, tried to install via GUI:

```
$ ./iobroker add zwave
npm install iobroker.zwave --production --prefix "/opt/iobroker" (System call)
find: unrecognized: -printfBusyBox v1.24.2 (2016-08-12 14:38:34 GMT) multi-call binary.

Usage: find [-HL] [PATH]... [OPTIONS] [ACTIONS]

Search for files and perform actions on them.
First failed action stops processing of current file.
Defaults: PATH is current directory, action is '-print'

    -L,-follow  Follow symlinks
    -H      ...on command line only
    -xdev       Don't descend directories on other filesystems
    -maxdepth N Descend at most N levels. -maxdepth 0 applies
            actions to command line arguments only
    -mindepth N Don't act on first N levels
    -depth      Act on directory *after* traversing it

Actions:
    ( ACTIONS ) Group actions for -o / -a
    ! ACT       Invert ACT's success/failure
    ACT1 [-a] ACT2  If ACT1 fails, stop, else do ACT2
    ACT1 -o ACT2    If ACT1 succeeds, stop, else do ACT2
            Note: -a has higher priority than -o
    -name PATTERN   Match file name (w/o directory name) to PATTERN
    -iname PATTERN  Case insensitive -name
    -path PATTERN   Match path to PATTERN
    -ipath PATTERN  Case insensitive -path
    -regex PATTERN  Match path to regex PATTERN
    -type X     File type is X (one of: f,d,l,b,c,...)
    -perm MASK  At least one mask bit (+MASK), all bits (-MASK),
            or exactly MASK bits are set in file's mode
    -mtime DAYS mtime is greater than (+N), less than (-N),
            or exactly N days in the past
    -mmin MINS  mtime is greater than (+N), less than (-N),
            or exactly N minutes in the past
    -newer FILE mtime is more recent than FILE's
    -inum N     File has inode number N
    -user NAME/ID   File is owned by given user
    -group NAME/ID  File is owned by given group
    -size N[bck]    File size is N (c:bytes,k:kbytes,b:512 bytes(def.))
            +/-N: file size is bigger/smaller than N
    -links N    Number of links is greater than (+N), less than (-N),
            or exactly N
    -prune      If current file is directory, don't descend into it
If none of the following actions is specified, -print is assumed
    -print      Print file name
    -print0     Print file name, NUL terminated
    -exec CMD ARG ; Run CMD with all instances of {} replaced by
            file name. Fails if CMD exits with nonzero
    -exec CMD ARG + Run CMD with {} replaced by list of file names
    -delete     Delete current file/directory. Turns on -depth option

gyp: Call to 'find /usr/local -type d ! -perm -g+r,u+r,o+r -prune -o -type d -name 'pkgconfig' -printf "%p:" | sed s/:$//g' returned exit status 0 while in binding.gyp. while trying to load binding.gyp
gyp

ERR! configure error 
gyp
 ERR! stack Error: `gyp` failed with exit code: 1gyp ERR! stack
     at ChildProcess.onCpExit (/usr/lib/node_modules/npm/node_modules/node-gyp/lib/configure.js:305:16)
gyp ERR! stack     at emitTwo (events.js:87:13)gyp ERR! stack     at ChildProcess.emit (events.js:172:7)

gyp ERR! stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:200:12)gyp ERR! System Linux 4.4.0-45-generic
gyp ERR! command "/usr/bin/node" "/usr/lib/node_modules/npm/node_modules/node-gyp/bin/node-gyp.js" "rebuild"

gyp ERR! cwd /opt/iobroker/node_modules/iobroker.zwave/node_modules/openzwave-sharedgyp ERR! node -v v4.6.1
gyp ERR! node-gyp -v v3.4.0

gyp ERR! 
not ok 
npm

ERR! Linux 4.4.0-45-generic
npm ERR! argv "/usr/bin/node" "/usr/bin/npm" "install" "iobroker.zwave" "--production" "--prefix" "/opt/iobroker"
npm ERR!
 node v4.6.1npm ERR! npm  v2.15.11

npm ERR! code ELIFECYCLE

npm ERR! openzwave-shared@1.1.9 install: `node-gyp rebuild`npm ERR! Exit status 1
npm ERR!
 npm ERR! Failed at the openzwave-shared@1.1.9 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the openzwave-shared package,
npm 
ERR! not with npm itself.npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild

npm ERR! You can get information on how to open an issue for this project with:npm ERR!     npm bugs openzwave-shared
npm ERR! Or if that isn't available, you can get their info via:
npm ERR! 
npm ERR!     npm owner ls openzwave-shared
npm ERR! There is likely additional logging output above.


npm ERR! Please include the following file with any support request:npm ERR!     /opt/iobroker/npm-debug.log

ERROR: host.keller Cannot install iobroker.zwave: 1
ERROR: process exited with code 25
```

**Comment by ekarak** [comment]
hi all, I've revamped the installation mechanism. please update and retry.

**Comment by Apollon77** [comment]
I close because ofg no response
