### ISSUE TITLE
Adapter not working under Windows 2019

### ISSUE THREAD

**Issue by HanSolo72** [ioBroker/ioBroker.zwave#77]
I want to use this Adapter under Windows Server 2019, in the device manager the USB Stick is recognized as COM3. As Devicename in the Adapter I tried COM3 and COM3:, but it isn't working.

Here is my log:

```
zwave.0 | 2019-09-09 23:03:43.852 | error | at Manager.<anonymous> (C:\Program Files\iobroker\SmartHome\node_modules\component-bind\index.js:21:15)
-- | -- | -- | --
zwave.0 | 2019-09-09 23:03:43.852 | error | at Socket.onpacket (C:\Program Files\iobroker\SmartHome\node_modules\socket.io-client\lib\socket.js:236:12)
zwave.0 | 2019-09-09 23:03:43.852 | error | at Socket.onack (C:\Program Files\iobroker\SmartHome\node_modules\socket.io-client\lib\socket.js:312:9)
zwave.0 | 2019-09-09 23:03:43.852 | error | at Socket.<anonymous> (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.zwave\main.js:117:21)
zwave.0 | 2019-09-09 23:03:43.852 | error | at setAllNotReady (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.zwave\main.js:594:9)
zwave.0 | 2019-09-09 23:03:43.852 | error | at main (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.zwave\main.js:1051:15)
zwave.0 | 2019-09-09 23:03:43.852 | error | at require (internal/modules/cjs/helpers.js:25:18)
zwave.0 | 2019-09-09 23:03:43.852 | error | at Module.require (internal/modules/cjs/loader.js:692:17)
zwave.0 | 2019-09-09 23:03:43.852 | error | at Function.Module._load (internal/modules/cjs/loader.js:562:25)
zwave.0 | 2019-09-09 23:03:43.852 | error | at Function.Module._resolveFilename (internal/modules/cjs/loader.js:636:15)
zwave.0 | 2019-09-09 23:03:43.852 | error | Error: Cannot find module 'openzwave-shared'
zwave.0 | 2019-09-09 23:03:43.851 | error | uncaught exception: Cannot find module 'openzwave-shared'
zwave.0 | 2019-09-09 23:03:43.764 | info | starting. Version 1.4.2 in C:/Program Files/iobroker/SmartHome/node_modules/iobroker.zwave, node: v10.16.3
```

**Comment by Apollon77** [comment]
Please post your adapter installation log because it seems that installation did not succeeded correctly

**Comment by HanSolo72** [comment]
```
host.Server	2019-09-11 19:46:22.822	error	iobroker host.Server Cannot install zwave
host.Server	2019-09-11 19:46:22.819	info	iobroker host.Server install adapter zwave
host.Server	2019-09-11 19:46:22.748	info	iobroker npm ERR! A complete log of this run can be found in:npm ERR! C:\Program Files\iobroker\SmartHome\env\npm-cache\_logs\2019-09-11T17_46_22_722Z-debug.log
host.Server	2019-09-11 19:46:22.747	info	iobroker
host.Server	2019-09-11 19:46:22.717	info	iobroker npm ERR! This is probably not a problem with npm. There is likely additional logging output above.
host.Server	2019-09-11 19:46:22.715	info	iobroker Failed at the openzwave-shared@1.4.8 preinstall script.
host.Server	2019-09-11 19:46:22.712	info	iobroker ERR!
host.Server	2019-09-11 19:46:22.710	info	iobroker
host.Server	2019-09-11 19:46:22.709	info	iobroker npm
host.Server	2019-09-11 19:46:22.705	info	iobroker
host.Server	2019-09-11 19:46:22.701	info	iobroker ERR!
host.Server	2019-09-11 19:46:22.698	info	iobroker
host.Server	2019-09-11 19:46:22.695	info	iobroker npm
host.Server	2019-09-11 19:46:22.687	info	iobroker ERR! Exit status 1
host.Server	2019-09-11 19:46:22.685	info	iobroker
host.Server	2019-09-11 19:46:22.683	info	iobroker npm
host.Server	2019-09-11 19:46:22.681	info	iobroker openzwave-shared@1.4.8 preinstall: `node lib/install-ozw.js`
host.Server	2019-09-11 19:46:22.681	info	iobroker ERR!
host.Server	2019-09-11 19:46:22.678	info	iobroker
host.Server	2019-09-11 19:46:22.677	info	iobroker npm
host.Server	2019-09-11 19:46:22.668	info	iobroker 1
host.Server	2019-09-11 19:46:22.666	info	iobroker errno
host.Server	2019-09-11 19:46:22.663	info	iobroker
host.Server	2019-09-11 19:46:22.655	info	iobroker ERR!
host.Server	2019-09-11 19:46:22.652	info	iobroker npm
host.Server	2019-09-11 19:46:22.651	info	iobroker ERR! code ELIFECYCLE
host.Server	2019-09-11 19:46:22.649	info	iobroker npm
host.Server	2019-09-11 19:46:22.211	info	iobroker win32 is currently not supported
host.Server	2019-09-11 19:46:21.836	info	iobroker _modules\iobroker.zwave\node_modules\openzwave-shared\lib\install-ozw.js:168:13) at Object.<anonymous> (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.zwave\node_modules\openzw
host.Server	2019-09-11 19:46:21.836	info	iobroker 38 throw err; ^ Error: Cannot find module 'C:\Windows\SERVIC~1\IOBROK~1\AppData\Local\Temp\ozwinstall-7ye84d/node_modules/request' at Function.Module._resolveFilename (intern
host.Server	2019-09-11 19:46:21.836	info	iobroker internal/modules/cjs/loader.js:6
host.Server	2019-09-11 19:46:21.829	info	iobroker npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks f
host.Server	2019-09-11 19:45:08.960	info	iobroker npm install iobroker.zwave@1.4.2 --unsafe-perm --production --save --prefix "C:/Program Files/iobroker/SmartHome" (System call)
host.Server	2019-09-11 19:45:08.958	info	iobroker NPM version: 6.9.0
host.Server	2019-09-11 19:45:06.158	info	iobroker host.Server install adapter zwave
host.Server	2019-09-11 19:45:06.099	info	iobroker npm ERR! A complete log of this run can be found in:npm ERR! C:\Program Files\iobroker\SmartHome\env\npm-cache\_logs\2019-09-11T17_45_06_086Z-debug.log
host.Server	2019-09-11 19:45:06.099	info	iobroker
host.Server	2019-09-11 19:45:06.056	info	iobroker This is probably not a problem with npm. There is likely additional logging output above.
host.Server	2019-09-11 19:45:06.056	info	iobroker ERR!
host.Server	2019-09-11 19:45:06.056	info	iobroker npm
host.Server	2019-09-11 19:45:06.056	info	iobroker Failed at the openzwave-shared@1.4.8 preinstall script.
host.Server	2019-09-11 19:45:06.056	info	iobroker ERR!
host.Server	2019-09-11 19:45:06.056	info	iobroker
host.Server	2019-09-11 19:45:06.055	info	iobroker npm
host.Server	2019-09-11 19:45:06.048	info	iobroker ERR!
host.Server	2019-09-11 19:45:06.046	info	iobroker Exit status 1npm
host.Server	2019-09-11 19:45:06.045	info	iobroker ERR!
host.Server	2019-09-11 19:45:06.044	info	iobroker openzwave-shared@1.4.8 preinstall: `node lib/install-ozw.js`npm
host.Server	2019-09-11 19:45:06.042	info	iobroker ERR!
host.Server	2019-09-11 19:45:06.042	info	iobroker
host.Server	2019-09-11 19:45:06.041	info	iobroker npm
host.Server	2019-09-11 19:45:06.028	info	iobroker errno 1
host.Server	2019-09-11 19:45:06.027	info	iobroker npm ERR!
host.Server	2019-09-11 19:45:06.026	info	iobroker ERR! code ELIFECYCLE
host.Server	2019-09-11 19:45:06.024	info	iobroker npm
host.Server	2019-09-11 19:45:05.614	info	iobroker win32 is currently not supported
host.Server	2019-09-11 19:45:05.221	info	iobroker Load (internal/modules/cjs/loader.js:593:12)
host.Server	2019-09-11 19:45:05.221	info	iobroker iobroker\SmartHome\node_modules\iobroker.zwave\node_modules\openzwave-shared\lib\install-ozw.js:223:12) at Module._compile (internal/modules/cjs/loader.js:778:30) at Object.Module._e
host.Server	2019-09-11 19:45:05.221	info	iobroker ernal/modules/cjs/helpers.js:25:18) at Module.module.exports (C:\Program Files\iobroker\SmartHome\node_modules\iobroker.zwave\node_modules\openzwave-shared\lib\install-ozw.js:168:13)
host.Server	2019-09-11 19:45:05.221	info	iobroker er.js:638 throw err; ^ Error: Cannot find module 'C:\Windows\SERVIC~1\IOBROK~1\AppData\Local\Temp\ozwinstall-yv1kd8/node_modules/request' at Function.Module._resolveFilename
host.Server	2019-09-11 19:45:05.220	info	iobroker internal/modules/cjs/load
host.Server	2019-09-11 19:45:05.212	info	iobroker npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks f
host.Server	2019-09-11 19:43:51.203	info	iobroker npm install iobroker.zwave@1.4.2 --unsafe-perm --production --save --prefix "C:/Program Files/iobroker/SmartHome" (System call)
host.Server	2019-09-11 19:43:51.203	info	iobroker NPM version: 6.9.0
host.Server	2019-09-11 19:43:48.362	info	iobroker host.Server install adapter zwave
host.Server	2019-09-11 19:43:48.283	info	iobroker npm ERR! A complete log of this run can be found in:npm ERR! C:\Program Files\iobroker\SmartHome\env\npm-cache\_logs\2019-09-11T17_43_48_276Z-debug.log
host.Server	2019-09-11 19:43:48.281	info	iobroker
host.Server	2019-09-11 19:43:48.253	info	iobroker This is probably not a problem with npm. There is likely additional logging output above.
host.Server	2019-09-11 19:43:48.251	info	iobroker ERR!
host.Server	2019-09-11 19:43:48.250	info	iobroker npm
host.Server	2019-09-11 19:43:48.248	info	iobroker ERR! Failed at the openzwave-shared@1.4.8 preinstall script.
host.Server	2019-09-11 19:43:48.246	info	iobroker npm
host.Server	2019-09-11 19:43:48.245	info	iobroker ERR!
host.Server	2019-09-11 19:43:48.243	info	iobroker npm
host.Server	2019-09-11 19:43:48.242	info	iobroker Exit status 1
host.Server	2019-09-11 19:43:48.240	info	iobroker ERR!
host.Server	2019-09-11 19:43:48.235	info	iobroker
host.Server	2019-09-11 19:43:48.231	info	iobroker npm
host.Server	2019-09-11 19:43:48.229	info	iobroker openzwave-shared@1.4.8 preinstall: `node lib/install-ozw.js`
host.Server	2019-09-11 19:43:48.228	info	iobroker npm ERR!
host.Server	2019-09-11 19:43:48.225	info	iobroker npm ERR! errno 1
host.Server	2019-09-11 19:43:48.224	info	iobroker ERR! code ELIFECYCLE
host.Server	2019-09-11 19:43:48.222	info	iobroker npm
host.Server	2019-09-11 19:43:47.909	info	iobroker win32 is currently not supported
host.Server	2019-09-11 19:43:47.453	info	iobroker npm WARN deprecated wrench@1.5.9: wrench.js is deprecated! You should check out fs-extra (https://github.com/jprichardson/node-fs-extra) for any operations you were using wrench for. Thanks f
host.Server	2019-09-11 19:42:34.244	info	iobroker npm install iobroker.zwave@1.4.2 --unsafe-perm --production --save --prefix "C:/Program Files/iobroker/SmartHome" (System call)
host.Server	2019-09-11 19:42:31.864	info	iobroker NPM version: 6.9.0

```

**Comment by AlCalzone** [comment]
The problem is that there is currently no foolproof way to compile the required dependencies on windows.
