### ISSUE TITLE
Problem npm-Version nach Aktualisierung

### ISSUE THREAD

**Issue by Ruler1983** [ioBroker/ioBroker.zwave#95]
Hallo an alle habe nach den letzten beiden Aktualisierungen immer das Problem das er mir einen Fehler mit der npm Version Anzeigt .
Anbei der Auszug der Logfile 

host.raspberrypi | 2019-11-13 08:56:59.617 | error | instance system.adapter.zwave.0 terminated with code 0 (OK)
-- | -- | -- | --
host.raspberrypi | 2019-11-13 08:56:59.616 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
host.raspberrypi | 2019-11-13 08:56:59.616 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:812:32)
host.raspberrypi | 2019-11-13 08:56:59.616 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
host.raspberrypi | 2019-11-13 08:56:59.616 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:956:30)
host.raspberrypi | 2019-11-13 08:56:59.616 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zwave/node_modules/openzwave-shared/lib/openzwave-shared.js:27:19)
host.raspberrypi | 2019-11-13 08:56:59.616 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
host.raspberrypi | 2019-11-13 08:56:59.616 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:849:19)
host.raspberrypi | 2019-11-13 08:56:59.616 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
host.raspberrypi | 2019-11-13 08:56:59.615 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:812:32)
host.raspberrypi | 2019-11-13 08:56:59.615 | error | Caught by controller[0]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
host.raspberrypi | 2019-11-13 08:56:59.615 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.raspberrypi | 2019-11-13 08:56:59.615 | error | Caught by controller[0]: NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
host.raspberrypi | 2019-11-13 08:56:59.615 | error | Caught by controller[0]: NODE_MODULE_VERSION 57. This version of Node.js requires
host.raspberrypi | 2019-11-13 08:56:59.615 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.raspberrypi | 2019-11-13 08:56:59.614 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/iobroker.zwave/node_modules/openzwave-shared/build/Release/openzwave_shared.node'
zwave.0 | 2019-11-13 08:56:59.581 | error | uncaught exception: The module '/opt/iobroker/node_modules/iobroker.zwave/node_modules/openzwave-shared/build/Release/openzwave_shared.node' was compiled against a different Node.js version using NODE
zwave.0 | 2019-11-13 08:56:59.473 | info | starting. Version 1.6.3 in /opt/iobroker/node_modules/iobroker.zwave, node: v12.13.0
host.raspberrypi | 2019-11-13 08:56:58.326 | info | instance system.adapter.zwave.0 started with pid 9860
host.raspberrypi | 2019-11-13 08:56:28.301 | info | Restart adapter system.adapter.zwave.0 because enabled

Letztes mal hatte ich den Rasberry komplett neu Aufgesetzt da alle Lösungen mit npm reinstall nicht geholfen hatten die ich im netz finden konnte.
Hoffe ihr könnt mir weiterhelfen um eine schnellere Lösung zu finden.
Danke im Vorraus ist mein erster Post

**Comment by AlCalzone** [comment]
```
cd /opt/iobroker/node_modules/iobroker.zwave/node_modules/openzwave-shared
npm install --production
```
sollte helfen.

**Comment by Ruler1983** [comment]
Hi AICalzone
erstmal danke für die schnelle Antwort.
Ich habe in das Verzeichniss gewechselt npm install --production eingegeben und Neustart
jedoch gleiche Fehlermeldung



host.raspberrypi | 2019-11-13 14:25:52.573 | error | instance system.adapter.zwave.0 terminated with code 0 (OK)
-- | -- | -- | --
host.raspberrypi | 2019-11-13 14:25:52.573 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
host.raspberrypi | 2019-11-13 14:25:52.573 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:812:32)
host.raspberrypi | 2019-11-13 14:25:52.573 | error | Caught by controller[0]:     at Object.Module._extensions..js (internal/modules/cjs/loader.js:973:10)
host.raspberrypi | 2019-11-13 14:25:52.573 | error | Caught by controller[0]:     at Module._compile (internal/modules/cjs/loader.js:956:30)
host.raspberrypi | 2019-11-13 14:25:52.573 | error | Caught by controller[0]:     at Object.<anonymous> (/opt/iobroker/node_modules/iobroker.zwave/node_modules/openzwave-shared/lib/openzwave-shared.js:27:19)
host.raspberrypi | 2019-11-13 14:25:52.573 | error | Caught by controller[0]:     at require (internal/modules/cjs/helpers.js:74:18)
host.raspberrypi | 2019-11-13 14:25:52.573 | error | Caught by controller[0]:     at Module.require (internal/modules/cjs/loader.js:849:19)
host.raspberrypi | 2019-11-13 14:25:52.572 | error | Caught by controller[0]:     at Function.Module._load (internal/modules/cjs/loader.js:724:14)
host.raspberrypi | 2019-11-13 14:25:52.572 | error | Caught by controller[0]:     at Module.load (internal/modules/cjs/loader.js:812:32)
host.raspberrypi | 2019-11-13 14:25:52.572 | error | Caught by controller[0]:     at Object.Module._extensions..node (internal/modules/cjs/loader.js:1003:18)
host.raspberrypi | 2019-11-13 14:25:52.572 | error | Caught by controller[0]: the module (for instance, using `npm rebuild` or `npm install`).
host.raspberrypi | 2019-11-13 14:25:52.572 | error | Caught by controller[0]: NODE_MODULE_VERSION 72. Please try re-compiling or re-installing
host.raspberrypi | 2019-11-13 14:25:52.572 | error | Caught by controller[0]: NODE_MODULE_VERSION 57. This version of Node.js requires
host.raspberrypi | 2019-11-13 14:25:52.572 | error | Caught by controller[0]: was compiled against a different Node.js version using
host.raspberrypi | 2019-11-13 14:25:52.571 | error | Caught by controller[0]: Error: The module '/opt/iobroker/node_modules/iobroker.zwave/node_modules/openzwave-shared/build/Release/openzwave_shared.node'
zwave.0 | 2019-11-13 14:25:52.426 | info | starting. Version 1.6.3 in /opt/iobroker/node_modules/iobroker.zwave, node: v12.13.0
host.raspberrypi | 2019-11-13 14:25:51.295 | info | instance system.adapter.zwave.0 started with pid 969
host.raspberrypi | 2019-11-13 14:25:21.288 | info | Restart adapter system.adapter.zwave.0 because enabled

**Comment by AlCalzone** [comment]
Ok das klingt mir schwer danach, dass zwei unterschiedliche Node-Versionen installiert sind. Dieser Fall ist im Forum zu Genüge behandelt, bitte mal dort nach der Lösung suchen.

**Comment by Ruler1983** [comment]
Ok super dann such ich mal weiter Dankeschön

**Comment by carsten19** [comment]
@Ruler1983 Problem gelöst?
